### DISCUSSION TITLE
Auto3DSeg KiTS23 Performance

### DISCUSSION THREAD

**Discussion by mibaumgartner** [Project-MONAI/tutorials#1644] [General]
Hi, I have trained Auto3DSeg on a single fold of the KiTS23 dataset with hierarchical labels (as defined in https://github.com/Project-MONAI/tutorials/pull/1627/files but without additional manual tuning of parameters). While SegResNet performed pretty well, DiNTs and Swin UNETR performed uncharacteristically bad (20-30 Dice points worse). Any ideas how to fix this? 

Best,
Michael 

task.yaml 
```yaml
datalist: ./data_list.json
dataroot: [path to dir here; removed for discussion on Github]
modality: CT

class_names:
  - { name: kidney_and_mass, index: [1,2,3] }
  - { name: mass, index: [2,3] }
  - { name: tumor, index: [2] }
sigmoid: true
```
